### ISSUE TITLE
read Algerian ID card using nfc

### ISSUE THREAD

**Issue by Zidoun-Abdou** [mustafa0khalifa/smart_ai_scan#1]
I want to use your project to read an algerian ID Card using NFC. I got this error: "Tag was not valid". can you help me please?

**Comment by zamirszn** [comment]
> I want to use your project to read an algerian ID Card using NFC. I got this error: "Tag was not valid". can you help me please?

hello were you able to do this

**Comment by Zidoun-Abdou** [comment]
> > I want to use your project to read an algerian ID Card using NFC. I got this error: "Tag was not valid". can you help me please?
> 
> hello were you able to do this

Yes using, Regula package but it's not free, or you can create your own algorithm + dmrtd library but it's complicated.

**Comment by zamirszn** [comment]
> > > I want to use your project to read an algerian ID Card using NFC. I got this error: "Tag was not valid". can you help me please?
> > 
> > hello were you able to do this
> 
> Yes using, Regula package but it's not free, or you can create your own algorithm + dmrtd library but it's complicated.

I used dmrtd + mrz_scanner I was able to get it working with passports and ID cards except for Algerian id cards , how much did it cost you to implement using Regula

**Comment by Zidoun-Abdou** [comment]
> > > > I want to use your project to read an algerian ID Card using NFC. I got this error: "Tag was not valid". can you help me please?
> > > 
> > > 
> > > hello were you able to do this
> > 
> > 
> > Yes using, Regula package but it's not free, or you can create your own algorithm + dmrtd library but it's complicated.
> 
> I used dmrtd + mrz_scanner I was able to get it working with passports and ID cards except for Algerian id cards , how much did it cost you to implement using Regula

It depends on your use, contact directly regula, they have a good support

**Comment by zamirszn** [comment]
> > > > > I want to use your project to read an algerian ID Card using NFC. I got this error: "Tag was not valid". can you help me please?
> > > > 
> > > > 
> > > > hello were you able to do this
> > > 
> > > 
> > > Yes using, Regula package but it's not free, or you can create your own algorithm + dmrtd library but it's complicated.
> > 
> > I used dmrtd + mrz_scanner I was able to get it working with passports and ID cards except for Algerian id cards , how much did it cost you to implement using Regula
> 
> It depends on your use, contact directly regula, they have a good support 

Alright thank you

**Comment by zamirszn** [comment]
> > > > > I want to use your project to read an algerian ID Card using NFC. I got this error: "Tag was not valid". can you help me please?
> > > > 
> > > > 
> > > > hello were you able to do this
> > > 
> > > 
> > > Yes using, Regula package but it's not free, or you can create your own algorithm + dmrtd library but it's complicated.
> > 
> > I used dmrtd + mrz_scanner I was able to get it working with passports and ID cards except for Algerian id cards , how much did it cost you to implement using Regula
> 
> It depends on your use, contact directly regula, they have a good support 

Hello sorry to bother you , I reached out to their support , my mail only got acknowledged I'm yet to get a response to my question , I'm trying to use the SDK for my app but my app is an offline for security , do you by any chance know if they offer offline licence , I've going through their docs couldn't find something that answers my question , thank you
